### ISSUE TITLE
[Suggestion] QoL Mod suggestions

### ISSUE THREAD

**Issue by ThePoleThatFishes** [Lach01298/Quanta#1]
Please add the following QoL mods for the next Quanta version:
1) Crafting Tweaks - Adds buttons to balance grid, spread grid, empty grid and rotate grid for more convenience in crafting
2) Controlling - Adds searching capability to controls menu per mod and per key, shows conflicts and unbound keys
3) Tomb Many Graves 2 - Grave mod
4) A mod for a crafting station like Tinkers' one, without Tinkers'?

**Comment by Lach01298** [comment]
1 and 2 seem reasonable. 
3: I actually don't what a graves mod. 
4: could you suggest a mod that does this.

**Comment by ThePoleThatFishes** [comment]
Here's a crafting station mod: https://www.curseforge.com/minecraft/mc-mods/crafting-station/files/2825047

**Comment by Lach01298** [comment]
added in 0.6
