### ISSUE TITLE
[SUGGESTION] More realistic steel production

### ISSUE THREAD

**Issue by Gliese-832-c** [Lach01298/Quanta#13]
Steel should be made from iron ore directly instead of iron ingots. I suppose the iron to steel option could be there for those who want to convert their stockpiles of iron into steel, but the main method should be turning iron ore into steel.

If you think that that would be OP, there is one way to gate it, and that is to make it require iron oxide (i.e. crushed iron ore), that way people will need to construct at least a crusher and some power source to be able to do that.

**Comment by Lach01298** [comment]
No
