### ISSUE TITLE
[SUGGESTION] Bricks should use less cement

### ISSUE THREAD

**Issue by Gliese-832-c** [Lach01298/Quanta#14]
Bricks use an annoying amount of cement. A stack of cement will only get you half a stack of brick blocks. I suggest one cement in the middle surrounded by 8 brick items for 4 brick blocks, or 2 cement - one on the left and one on the right of the crafting table - with 7 brick items, for 3 or 4 brick blocks.

**Comment by Lach01298** [comment]
Probably change it

**Comment by Lach01298** [comment]
I made the cement recipe give 12 instead of 8, so less CaO is needed
