### ISSUE TITLE
[Suggestion] Turbine coil rebalancing

### ISSUE THREAD

**Issue by ThePoleThatFishes** [Lach01298/Quanta#16]
The turbine coils are currently very unbalanced.
One can do just copper and silver coils and get a lot of efficiency without the more expensive coils.
Based on that I wanted to suggest a rebalance to bring the coils more in line:

Silver 110% -> 95%
Gold 105% -> 100%
Magnesium 100% -> 105%
Aluminum 95% -> 110%
(Basically switch silver and aluminum, gold and magnesium coil efficiencies)

**Comment by Lach01298** [comment]
0.7.1
