### ISSUE TITLE
[Bug] Soda lime advancement

### ISSUE THREAD

**Issue by ThePoleThatFishes** [Lach01298/Quanta#2]
In pre-industrial age advancements, the player is required to get sodium carbonate from kelp to make glass, but what you actually get is soda lime mix (what the advancement should ask for)
Also blocks glass advancement from completion.

**Comment by Lach01298** [comment]
I looked and the glass achievements requires both sodium carbonate and calcium oxide to be complete. The glass achievement only looks for glass blocks. So is there a bug?

**Comment by ThePoleThatFishes** [comment]
I think the bug exists because:
Kelp smelting makes soda lime mix (advancement says just sodium carbonate)
Glass needs 2 sand and soda lime mix 
Soda lime mix is mix of lime and sodium carbonate, but sodium carbonate is obtained way later in the pack

**Comment by Lach01298** [comment]
kelp smelting should make sodium carbonate

**Comment by Lach01298** [comment]
oh i see yeah that a bug

**Comment by Lach01298** [comment]
fixed in 0.6
