### ISSUE TITLE
[BUG] The crusher has the wrong recipes

### ISSUE THREAD

**Issue by qcjwr87qnmw4** [Lach01298/Quanta#21]
The crusher has the wrong recipes.
![2022-03-27_16 57 21](https://user-images.githubusercontent.com/101476463/160285441-ccd89ed6-9c65-403f-a6eb-2b330b3cc490.png)

**Comment by qcjwr87qnmw4** [comment]
And it is also impossible to get gold dust from ore in it.

**Comment by Lach01298** [comment]
fixed in 0.7.2
