### ISSUE TITLE
Make uranium sheetmetal require U-238

### ISSUE THREAD

**Issue by Arsenilium** [Lach01298/Quanta#26]
I suggest uranium sheetmetal be made from U-238 since it's already an excellent shielding material against solar/cosmic radiation on other planets. This would also give use to the huge amount of depleted uranium from enrichment. Lastly, there should be a way to make UF6 from uranium ingots; I got a bunch lying around from before the update that overhauled enrichment.

**Comment by joendter** [comment]
I currently see no use for  Uranium Plates except for decoration, but ig it makes sense to make them out of U-238

**Comment by joendter** [comment]
implemented in [1b19821](https://github.com/Lach01298/Quanta/commit/1b198210a6abb310868d66b0b551658d5df0b11a)
