### ISSUE TITLE
strange loop in progression

### ISSUE THREAD

**Issue by falizure** [Lach01298/Quanta#4]
i'm not sure if this is intentional but to make many of magneticrafts machines including a grinder requires a circuit, the circuit requires materials that come from sieving gravel types of some resources, but to make gravel you need the grinder, i think you can technically get by this by making a immersive crusher and if that is intentional then fair enough but it doesn't seam clear whether your supposed to focus on magneticraft or immersive first or if its some mix of the 2,

**Comment by Gliese-832-c** [comment]
I'm pretty sure it's intentional to do IE first, then MgC.

**Comment by falizure** [comment]
ok, but the advancement list has the mgc sieve early on because you need it for some other resource.
